name: Build All Platforms
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build Tauri app
      run: npm run tauri build
    
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: |
          src-tauri/target/release/bundle/msi/*.msi
          src-tauri/target/release/bundle/nsis/*.exe
          src-tauri/target/release/SynchDoc.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-apple-darwin,x86_64-apple-darwin
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build Tauri app (Apple Silicon)
      run: npm run tauri build -- --target aarch64-apple-darwin
    
    - name: Build Tauri app (Intel)
      run: npm run tauri build -- --target x86_64-apple-darwin
    
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: |
          src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
          src-tauri/target/aarch64-apple-darwin/release/bundle/macos/*.app
          src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/*.dmg
          src-tauri/target/x86_64-apple-darwin/release/bundle/macos/*.app
          src-tauri/target/aarch64-apple-darwin/release/SynchDoc
          src-tauri/target/x86_64-apple-darwin/release/SynchDoc

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-gnu
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build Tauri app
      run: npm run tauri build
    
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: |
          src-tauri/target/release/bundle/deb/*.deb
          src-tauri/target/release/bundle/rpm/*.rpm
          src-tauri/target/release/bundle/appimage/*.AppImage
          src-tauri/target/release/SynchDoc

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/windows-build/*.msi
          artifacts/windows-build/*.exe
          artifacts/macos-build/*.dmg
          artifacts/macos-build/*.app
          artifacts/linux-build/*.deb
          artifacts/linux-build/*.rpm
          artifacts/linux-build/*.AppImage
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
